src/ipyopt_module.cpp: Add missing #include <optional>
Fixes
src/ipyopt_module.cpp:241:13: error: ‘optional’ in namespace ‘std’ does not name a template type
  241 | static std::optional<IpoptOptionValue> py_unpack(PyObject *obj) {